### ISSUE TITLE
[Tracking Issue] Tests

### ISSUE THREAD

**Issue by jlord** [jlord/reporobot#23]
A tracking issue for building a suite of tests for @reporobot :cat: :sparkler: 

_Currently only I can run these tests as I have the tokens for @reporobot's account :grin:_
### Test Scenarios
- [ ] Correct Pull Request
- [x] Incorrect PR: Wrong branch name [#22](https://github.com/jlord/reporobot/pull/22)
- [x] Incorrect PR: File is empty
- [x] Incorrect PR: Wrong Filename
- [x] Incorrect PR: Too many files [#23](https://github.com/jlord/reporobot/pull/23)
### Other bits
- [ ] scripts
  - [ ] run suite
  - [ ] run each test
